export const API_TAGS = {
  AUTH: ["Auth"],
  HERO: ["HERO SECTION"],
  BOTTOM: ["BOTTOM SECTION"],
  FOOTER: ["FOOTER"],
  FAQ: ["FAQ"],
  OURADVANTAGE: ["OUR-ADVANTAGE"],
  OURSERVICE: ["OUR-SERVICE"],
  REGULATION: ["REGULATION"],
  REQUIREMENTWITHDRIVER: ["REQUIREMENT WITH DRIVER"],
  REQUIREMENTNODRIVER: ["REQUIREMENT NO DRIVER"],
  REQUIREMENTNOTE: ["REQUIREMENT NOTE"],
  COMPANYABOUT: ["COMPANY ABOUT"],
};
